SELECT GROUP_CONCAT(CONCAT("'",COLUMN_NAME,"'"))
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'properties'
ORDER BY ORDINAL_POSITION
UNION ALL
SELECT *
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '\\'
LINES TERMINATED BY '\n'
FROM properties;
